spring:
  application:
    name: system-order-uniform

  threads:
    virtual:
      enabled: true
  web:
    error:
      include-stacktrace: on_param

server:
  servlet:
    context-path: /

database:
    url: ${DB_URL:localhost}:${DB_PORT:3306}
    username: ${LOCAL_USERNAME:pedro}
    password: ${LOCAL_PASSWORD:pedro}